default: &default
  source_entry_path: app/javascript/packs
  source_files_exts: .js, .jsx, .ts, .tsx
  source_path: app/javascript
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  check_yarn_integrity: true
  extract_css: true
  static_assets_extensions: .eot, .woff, .woff2, .ttf, .svg
  extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  dev_server:
    hmr: false
    host: localhost
    port: 3035
    public: localhost:3035
    https: false
    compress: true
    timeout: 60000
    headers:
      'Access-Control-Allow-Origin': '*'
  webpack:
    # Ensure this is the latest Webpack configuration
    config: config/webpack/production.js

development:
  <<: *default
  source_entry_path: packs
  extract_css: true
  cache_manifest: false
  dev_server:
    public: localhost:3035

production:
  <<: *default
  source_entry_path: packs
  extract_css: true
  cache_manifest: false
  dev_server:
    public: localhost:3035
